
default: &default
  adapter: mysql2
  encoding: latin1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: panOPen
  username: root
  password: 525
  socket: /var/run/mysqld/mysqld.sock
  host: localhost


test:
  <<: *default
  database: panOPen

production:
  <<: *default
  database: panOPen
